### ISSUE TITLE
EndFrame test

### ISSUE THREAD

**Issue by Karyum** [FACN8/PetHub#30]
https://github.com/FACN8/PetHub/blob/master/src/components/tests/EndFrame.test.js#L26-L28

why did you add the `.not` method ? 
i'm asking cause at the top you set the localstorage items but when you get them at the bottom they are not the same values?

**Comment by LogicX1** [comment]
The test was to see if endframe did clear the local storage, so first i set items with values ,then the test is to check if the items in local storage does not have the values we set, because they should just be undefined since we cleared them.
We could I guess have tested if the item exists or not .
